### ISSUE TITLE
tag list without href

### ISSUE THREAD

**Issue by guilamu** [Surbma/surbma-divi-project-shortcodes#1]
Hello Surbma,

I'm a heavy user of your divi gravity forms addon., We've already talk on the wordpress plugin repositories. I've submitied you a couple of bugs a few months ago.

I just stumbled upon one of your great plugins again, the divi project shortcodes!

It does the job a little too well for me, I would need to be able to display shortcodes without them to be clickable (no href).

Is that possible?

Best regards,

**Comment by Surbma** [comment]
Hi guilamu,

I'm really happy, that you are using my plugins.

There is no way to show terms list without links, this is a WordPress function:
https://codex.wordpress.org/Function_Reference/get_the_term_list

My only idea is to trick with css:
`.not-active a {pointer-events: none;cursor: default;}`

So you need to give the shortcodes a wrapper block:
`<div class="not-active">[project-category-list]</div>`

This trick will definitely do the job for you. ;)

**Comment by guilamu** [comment]
Well, in the end I've made my own shortcode:

<?php
/*-----------Display project tag-----------------------*/
add_shortcode( 'display_tags', 'display_custom_post_type' );

function display_custom_post_type(){
   global $post;
   $output = get_post_type( $post );
   if ('project' === get_post_type( $post ) ) {
      $terms = get_the_terms( $post->ID, 'project_tag' );
      $output="<ul class='project-tags'>";
      foreach ($terms as $term) {
         $output .= $term->name;
      }
      $output .="</ul>";
   }
   return $output;
}

**Comment by Surbma** [comment]
I'm glad, you have found a solution. :)
